<a href="https://colab.research.google.com/github/WittyWaithira/DifferentialPrivacy/blob/master/diffprivacy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# the number of entries in our database
num_entries = 5000

db = torch.rand(num_entries)> 0.5
db

tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8)

In [2]:
db = torch.rand(num_entries)> 0.5
db

tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8)

In [3]:
db.shape

torch.Size([5000])

In [4]:
db[0:5]

tensor([1, 0, 1, 0, 1], dtype=torch.uint8)

In [0]:
remove_index = 2

In [0]:
def get_parallel_db(db,remove_index):
  return torch.cat((db[0:remove_index],
                    db[remove_index+1:]))

In [18]:
get_parallel_db(db,0)

torch.Size([4999])

In [0]:
def get_parallel_dbs(db):
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db,i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs
  
  

In [0]:
pdbs = get_parallel_dbs(db)

In [30]:
pdbs

[tensor([0, 1, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 1, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 0,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0, 1], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 0

In [0]:
def create_db_and_parallels(num_entries):
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db,pdbs
  

In [0]:
db,pdbs = create_db_and_parallels(20)

In [36]:
db

tensor([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
       dtype=torch.uint8)

In [38]:
pdbs

[tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
        dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,