<a href="https://colab.research.google.com/github/WittyWaithira/DifferentialPrivacy/blob/master/diffprivacy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch

# the number of entries in our database
num_entries = 5000

db = torch.rand(num_entries)> 0.5
db

tensor([0, 0, 1,  ..., 1, 0, 1], dtype=torch.uint8)

In [8]:
db = torch.rand(num_entries)> 0.5
db

tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8)

In [9]:
db.shape

torch.Size([5000])

In [10]:
db[0:5]

tensor([0, 0, 0, 1, 1], dtype=torch.uint8)

In [0]:
remove_index = 2

In [0]:
def get_parallel_db(db,remove_index):
  return torch.cat((db[0:remove_index],
                    db[remove_index+1:]))

In [13]:
get_parallel_db(db,0)

tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb = get_parallel_db(db,i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs
  
  

In [0]:
pdbs = get_parallel_dbs(db)

In [16]:
pdbs

[tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 1, 1

In [0]:
def create_db_and_parallels(num_entries):
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db,pdbs
  

In [0]:
db,pdbs = create_db_and_parallels(20)

In [19]:
db

tensor([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
       dtype=torch.uint8)

In [20]:
pdbs

[tensor([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,

In [0]:
def query(db):
  return db.sum()

In [0]:
full_db_result = query(db)

In [0]:
sensitivity = 0
for pdb in pdbs:
  pdb_result = query(pdb)
  
  db_distance = torch.abs(pdb_result - full_db_result)
  
  if db_distance > sensitivity:
    sensitivity = db_distance
  
  

In [24]:
sensitivity

tensor(1)

In [0]:
def sensitivity (query,n_entries=1000):
  db,pdbs = create_db_and_parallels(n_entries)
  
  full_db_result = query(db)
  
  max_distance = 0
  for pdb in pdbs:
    pdb_result = query(pdb)
    db_distance = torch.abs(pdb_result - full_db_result)
    if db_distance > max_distance:
      max_distance = db_distance
  return max_distance

In [0]:
def query(db):
  return db.float().mean()

In [29]:
sensitivity(query)

tensor(0.0005)

In [0]:
def query(db,threshold=5):
  return (db.sum()>threshold).float()

In [42]:
for i in range(10):
  sens_f = sensitivity(query,n_entries = 10)
  print(sens_f)

tensor(1.)
0
0
0
0
0
tensor(1.)
0
tensor(1.)
tensor(1.)


In [0]:
db,_ = create_db_and_parallels(100)


In [0]:
pdb = get_parallel_db(db,remove_index=10)

In [46]:
db[10]

tensor(0, dtype=torch.uint8)

In [50]:
sum(db)

tensor(51, dtype=torch.uint8)

In [47]:
#differencing attack using sum query
sum(db)-sum(pdb)

tensor(0, dtype=torch.uint8)

In [49]:
#differencing attack using mean query

(sum(db).float()/len(db)) - (sum(pdb).float()/len(pdb))

tensor(-0.0052)

In [51]:
#differencing attack using threshold query

(sum(db).float()>50) - (sum(pdb).float()>50)

tensor(0, dtype=torch.uint8)